/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ThreadAffinity */

#ifndef _Included_ThreadAffinity
#define _Included_ThreadAffinity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ThreadAffinity
 * Method:    setThreadAffinity
 * Signature: (Ljava/util/BitSet;)V
 */
JNIEXPORT void JNICALL Java_ThreadAffinity_setThreadAffinity
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
